version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: maluser
      POSTGRES_PASSWORD: malpassword
      POSTGRES_DB: mal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
